homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
 ###################################################
 #                 Customization                   #
 ###################################################
  customize_glob:
      light.*:
        custom_ui_state_card: custom_light
           
  customize: !include packages/customize.yaml
    
###################################################
#                      Misc                       #
###################################################
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - 2001:DB8:ABCD::/48
    
panel_iframe: !include packages/iframe.yaml
  
    
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

scene: !include packages/scenes.yaml

input_boolean: !include packages/inputboolean.yaml

#google:
#  client_id: !secret googlecalendarID
#  client_secret: !secret googlecalendarSECRET
  
#remote:
#  - platform: harmony
#    name: Harmony
#    host: !secret harmonyhost

device_sun_light_trigger:
  light_group: group.livingroomlights
  light_profile: relax
 
notify:
  - name: sms
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notifysender
    starttls: true
    username: !secret notifyusername
    password: !secret notifypassword
    recipient:
      - !secret rorytext
    sender_name: My Home Assistant
  - name: smsboth
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notifysender
    starttls: true
    username: !secret notifyusername
    password: !secret notifypassword
    recipient:
      - !secret rorytext
      - !secret tracytext
  - name: smstracy
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notifysender
    starttls: true
    username: !secret notifyusername
    password: !secret notifypassword
    recipient:
      - !secret tracytext
    sender_name: My Home Assistant 
  - name: smsdad
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notifysender
    starttls: true
    username: !secret notifyusername
    password: !secret notifypassword
    recipient:
      - !secret dadtext
    sender_name: My Home Assistant 
  - name: smsbrennan
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret notifysender
    starttls: true
    username: !secret notifyusername
    password: !secret notifypassword
    recipient:
      - !secret brennantext
    sender_name: My Home Assistant     

###################################################
#                    Sensors                      #
###################################################
# Track the sun
sun:

 #Weather Prediction
sensor: !include packages/sensor.yaml
    
# Text to speech
#tts:
#  platform: google

group: !include packages/groups.yaml
automation:  !include_dir_merge_list packages/automations/
###################################################
#                    MQTT                         #
###################################################
octoprint:
  host: !secret octohost
  api_key: !secret octoapi
  
      
recorder:
  db_url: !secret db_url
  purge_days: 3
  
mqtt:
  broker: !secret mqttbroker
  port: !secret mqttport
  client_id: home-assistant-1
  username: !secret mqttusername
  password: !secret mqttpassword
  keepalive: 60

light:  
  - platform: mqtt_json  
    name: "Mancave LED"  
    state_topic: "bruh/sensornodemancave"  
    command_topic: "bruh/sensornodemancave/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0 
    
  - platform: mqtt_json  
    name: "Mainframe LED"  
    state_topic: "bruh/sensornodemainframe"  
    command_topic: "bruh/sensornodemainframe/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0 
   
  - platform: hue
    scan_interval: 5    
  
binary_sensor:
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/motion"
    name: "Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error
  
###################################################
#                    Trackers                     #
###################################################
#owntracks
device_tracker:
  - platform: owntracks
  
  - platform: tplink
    host: !secret tplinkhost
    username: !secret tplinkusername
    password: !secret tplinkpassword
    interval_seconds: 5
    consider_home: 180
    track_new_devices: yes

  
###################################################
#                    Devices                      #
###################################################
# Ecobee
ecobee:
  api_key: !secret ecobeeapi
  
media_player:
  - platform: plex
    scan_interval: 1
    
ios:

lutron_caseta:
    host: !secret lutronhost
    
envisalink:
  host: !secret alarmhost
  panel_type: !secret alarmtype 
  user_name: !secret alarmusername
  password: !secret alarmpassword
  code: !secret alarmcode
  port: !secret alarmport
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 15
  panic_type: Police
  zones:
    02:
      name: 'Front Entrance' 
      type: 'motion'
    03: 
      name: 'Livingroom'
      type: 'motion'
    04:
      name: 'basement'
      type: 'motion'
    05:
      name: 'basement window'
      type: 'opening'
    09:
      name: 'kitchen'
      type: 'motion'
    10:
      name: 'Front Door'
      type: 'opening'
    11: 
      name: 'Garage Door'
      type: 'opening'
    12:
      name: 'Deck Door'
      type: 'opening'
    13:
      name: 'Basement Door'
      type: 'opening'
    
  partitions:
    1:
      name: 'Sentinel'
   
     
###################################################
#                    Scripts                      #
###################################################    
script:  !include packages/scripts.yaml
switch:  !include packages/switches.yaml

camera:
  - platform: mjpeg
    mjpeg_url: !secret octomjpeg_url
    name: Replicator
  - platform: amcrest
    host: !secret amcrestip
    username: !secret amcrestusername
    password: !secret amcrestpass
    name: Front Entrance



