######################################################
#                   Thermostat and Alarm             #
###################################################### 
- alias: Thermostat to Away mode when away
  trigger:
    platform: state
    entity_id: input_boolean.homestatus
    from: 'on'
    to: 'off'
  action:
    service: climate.set_hold_mode
    entity_id: climate.thermostat
    data:
      hold_mode: 'away'
##########################################################################################   
- alias: Arm alarm when away
  trigger:
    platform: state
    entity_id: input_boolean.homestatus
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.alarmstatus
##########################################################################################      
- alias: Disarm alarm when home
  trigger:
    platform: state
    entity_id: input_boolean.homestatus
    from: 'off'
    to: 'on'          
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.alarmstatus
##########################################################################################               
- alias: arm boolean when armed
  trigger:
    platform: state
    entity_id: input_boolean.alarmstatus
    from: 'off'
    to: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.sentinel
      data: 
        code: !secret alarmcode
##########################################################################################
- alias: disarm boolean when disarmed
  trigger:
    platform: state
    entity_id: input_boolean.alarmstatus
    from: 'on'
    to: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.sentinel
      data: 
        code: !secret alarmcode
##########################################################################################
##########################################################################################      
######## IOS notifications for alarm     
##########################################################################################   
- alias: Notify when alarm disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.sentinel
    from: 'armed_home'
    to: 'disarmed'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Alarm disarmed'
##########################################################################################      
- alias: Notify when alarm armed
  trigger:
    platform: state
    entity_id: alarm_control_panel.sentinel
    from: 'disarmed'
    to: 'armed_home'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Alarm armed'
##########################################################################################
##Turn off panic      
- alias: stop alarm script  when disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.sentinel
    to: 'disarmed'
  action:
    - service: light.turn_on
      data:
        entity_id: group.all_lights
        color: white
        brightness: 255
##########################################################################################
##Basement Motion     
##########################################################################################
- alias: Notify basement motion w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.basement     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Motion in basement!'
##########################################################################################      
##Kitchen Motion
##########################################################################################
- alias: Notify kitchen motion w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Motion in kitchen!'
##########################################################################################      
##Livingroom Motion     
########################################################################################## 
- alias: Notify livingroom motion w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Motion in livingroom!'
##########################################################################################      
##Front Motion
##########################################################################################      
- alias: Notify front entrance motion w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.front_entrance     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    service: notify.sms
    data:
      title: "Sentinel"
      message: 'Motion in front entrance!'
##########################################################################################      
##Kitchen Door
##########################################################################################      
- alias: Notify kitchen door w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    - service: notify.sms
      data:
        title: "Sentinel"
        message: 'Kitchen entrance opened!'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_switches
##########################################################################################        
##Deck Door
##########################################################################################      
- alias: Notify deck door w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.deck_door     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    - service: notify.sms
      data:
        title: "Sentinel"
        message: 'Deck entrance opened!'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_switches
##########################################################################################        
##Front Door
##########################################################################################      
- alias: Notify front door w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.front_door     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    - service: notify.sms
      data:
        title: "Sentinel"
        message: 'Front entrance opened!'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_switches
##########################################################################################        
##Basement Door
##########################################################################################      
- alias: Notify basement door w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.basement_door     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    - service: notify.sms
      data:
        title: "Sentinel"
        message: 'Basement Door opened!'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_switches
##########################################################################################        
##Basement Window
##########################################################################################      
- alias: Notify basement window w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.basement_window     
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sentinel
    state: 'armed_home'
  action:
    - service: notify.sms
      data:
        title: "Sentinel"
        message: 'Basement window opened!'
    - service: light.turn_on
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_switches
##########################################################################################        
##Doorbell Chime
##########################################################################################      
- alias: Turn off chime w/ alarm on
  trigger:
    platform: state
    entity_id: input_boolean.alarmstatus
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.doorbell_chime
##########################################################################################      
- alias: Turn on chime w/ alarm off
  trigger:
    platform: state
    entity_id: input_boolean.alarmstatus
    from: 'on'
    to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.doorbell_chime
##########################################################################################        
##                            You left the door open notifications                       #
########################################################################################## 
##########################################################################################      
##Kitchen Door
##########################################################################################      
- alias: Notify if kitchen door left open
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door     
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.smsboth
    data:
      title: "Sentinel"
      message: 'Someone left the kitchen door open'
##########################################################################################        
##Deck Door
##########################################################################################      
- alias: Notify if deck door left open
  trigger:
    platform: state
    entity_id: binary_sensor.deck_door     
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.smsboth
    data:
      title: "Sentinel"
      message: 'Someone left the deck door open'
##########################################################################################        
##Front Door
##########################################################################################      
- alias: Notify front door w/ alarm armed
  trigger:
    platform: state
    entity_id: binary_sensor.front_door     
    to: 'on'
    for:
      minutes: 10
  action:
    service: notify.smsboth
    data:
      title: "Sentinel"
      message: 'Someone left the front door open'
##########################################################################################        
##Basement Door
##########################################################################################      
- alias: Notify if basement door left open
  trigger:
    platform: state
    entity_id: binary_sensor.basement_door     
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.smsboth
    data:
      title: "Sentinel"
      message: 'Someone left the basement door open'
##########################################################################################        
##Basement window
##########################################################################################       
- alias: Notify basement window left open 
  trigger:
    platform: state
    entity_id: binary_sensor.basement_window     
    to: 'on'
    for:
      minutes: 30
  action:
    service: notify.smsboth
    data:
      title: "Sentinel"
      message: 'Someone left the basement window open'    
##########################################################################################        
##Turn off alarm with front_entrance motion
##########################################################################################       
- alias: Turn off alarm with front_entrance motion 
  trigger:
    - platform: state
      entity_id: binary_sensor.front_entrance
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homestatus 
        state: 'on'
      - condition: time
        after: '05:00:00'
        before: '08:00:00'
      - condition: state
        entity_id:  input_boolean.alarmstatus
        state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.alarmstatus            
##########################################################################################        
##Arm Alarm at night with lights
##########################################################################################       
- alias: Turn on alarm when tracy light turned off after 10pm
  trigger:
    platform: state
    entity_id: light.tracy_bed     
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homestatus 
        state: 'on'
      - condition: time
        after: '22:00:00'
        before: '08:00:00'
      - condition: state
        entity_id:  input_boolean.alarmstatus
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.alarmstatus            
               
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        