######################################################
#                Basement Lights                     #
######################################################     
##########################################################################################
- alias: turn on the basement lights w/ motion 
  trigger:
    platform: state
    entity_id: binary_sensor.basement     
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.basement_lights
        state: 'off'        
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.basementmotion
##########################################################################################
- alias: turn on the basement lights w/  door
  trigger:
    platform: state
    entity_id: binary_sensor.basement_door      
    to: 'on'       
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.basementmotion
##########################################################################################    
- alias: Turn off basement light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.basement
    to: 'off'
    for:
      minutes: 3
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.basementmotion     
##########################################################################################     
- alias: turn on the basement lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.basementmotion     
    to: 'on'       
  action:
    service: scene.turn_on
    entity_id: scene.basement_dim
##########################################################################################     
- alias: turn off the basement lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.basementmotion     
    to: 'off'     
  action:
    service: light.turn_off
    entity_id: light.basement_lights

######################################################
#                Mancave                             #
######################################################
- alias: turn on multisensor led w/ motion in man cave
  trigger:
    platform: state
    entity_id: sensor.mancave_pir      
    to: 'motion detected'
  action:
    service: light.turn_on
    entity_id: light.mancave_led
- alias: turn off multisensor led w/ motion in man cave
  trigger:
    platform: state
    entity_id: sensor.mancave_pir      
    to: 'standby'
  action:
    service: light.turn_off
    entity_id: light.mancave_led
    














