######################################################
#                Kitchen  Lights                     #
######################################################  
##########################################################################################    
- alias: turn on the kitchen lights w/ motion
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen     
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: light.kitchen
        state: 'off' 
      - condition: or
        conditions:    
          - condition: state
            entity_id: group.livingroomlights 
            state: 'off'
          - condition: state
            entity_id: input_boolean.deckdoor
            state: 'on'        
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.kitchenmotion  
##########################################################################################     
- alias: turn on the kitchen lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.kitchenmotion     
    to: 'on'       
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_dim
##########################################################################################     
- alias: turn off the kitchen lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.kitchenmotion     
    to: 'off'     
  action:
    service: light.turn_off
    entity_id: light.kitchen
    
##########################################################################################    
- alias: Turn off kitchen light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: input_boolean.kitchenmotion
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.kitchen  
##########################################################################################
######################################################
#                Basement Lights                     #
######################################################     
##########################################################################################
- alias: turn on the basement lights w/ motion 
  trigger:
    platform: state
    entity_id: binary_sensor.basement     
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.basement_lights
        state: 'off'        
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.basementmotion
##########################################################################################
- alias: turn on the basement lights w/  door
  trigger:
    platform: state
    entity_id: binary_sensor.basement_door      
    to: 'on'       
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.basementmotion
##########################################################################################    
- alias: Turn off basement light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.basement
    to: 'off'
    for:
      minutes: 3
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.basementmotion     
##########################################################################################     
- alias: turn on the basement lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.basementmotion     
    to: 'on'       
  action:
    service: scene.turn_on
    entity_id: scene.basement_dim
##########################################################################################     
- alias: turn off the basement lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.basementmotion     
    to: 'off'     
  action:
    service: light.turn_off
    entity_id: light.basement_lights
    
##########################################################################################
######################################################
#                Livingroomights                     #
######################################################     
##########################################################################################
- alias: turn on the livingroom lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.deckdoor     
    to: 'on'       
  action:
    service: light.turn_on
    data:
      entity_id: group.livingroomlights
      transition: 10
      brightness: 201
      rgb_color: 255,45,0
    
##########################################################################################     
- alias: turn off the livingroom lights w/ boolean
  trigger:
    platform: state
    entity_id: input_boolean.deckdoor     
    to: 'off'     
  action:
    service: light.turn_off
    data:
      entity_id: group.livingroomlights
      transition: 20
##########################################################################################    
- alias: turn on the livingroom lights w/  door
  trigger:
    platform: state
    entity_id: binary_sensor.deck_door      
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset 
      - condition: state
        entity_id: binary_sensor.livingroom
        state: 'off'
      - condition: state
        entity_id: group.livingroomlights
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.deckdoor
##########################################################################################    
- alias: turn off the livingroom lights w/  door
  trigger:
    platform: state
    entity_id: binary_sensor.deck_door      
    to: 'off'
    for: 300
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset 
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.deckdoor

















