######################################################
#                 Arriving Home                      #
######################################################

##########################################################################################
- alias: turn on the kitchen lights
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.roryhome
    from: 'off'
    to: 'on'            
  action:
    service: light.turn_on
    entity_id: light.kitchen
##########################################################################################
- alias: turn on the kitchen lights tracy
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.tracyhome
    from: 'off'
    to: 'on'      
  condition:
    condition: sun
    after: sunset    
  action:
    service: light.turn_on
    entity_id: light.kitchen
##########################################################################################    
- alias: turn on the livingroom lights when home
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.homestatus
    from: 'off'
    to: 'on'      
  condition:
    condition: sun
    after: sunset  
  action:
    service: light.hue_activate_scene
    data:
      group_name: "Living room"
      scene_name: "Beige"       
##########################################################################################
######################################################
#                 Outside Lights                     #
######################################################
##########################################################################################
- alias: turn on front porch lights
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.roryhome, input_boolean.tracyhome
    from: 'off'
    to: 'on'      
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.front_porch
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'      
  action:
    service: light.turn_on
    entity_id: light.front_porch
##########################################################################################
##########################################################################################    
- alias: Turn off basement light 3 minutes after door closed
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.basement_door 
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: binary_sensor.basement
    state: 'off'    
  action:
    service: light.turn_off
    entity_id: light.basement_lights      
######################################################
#                 Turn Off all lights                #
######################################################
##########################################################################################      
- alias: Turn off Lights when everyone leaves
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.homestatus
    from: 'on'
    to: 'off'         
  action:
    service: script.lightsoff
########################################################################################## 
######################################################
#                 Octoprint light automation         #
######################################################
- alias: Turn on light while printing
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    to: 'Printing'
  action:
    service: switch.turn_on
    entity_id: switch.workshop
    
- alias: Turn off light while not printing
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    to: 'Operational'
    for:
      minutes: 15
  action:
    service: switch.turn_off
    entity_id: switch.workshop        
######################################################
#                 Hall light automation              #
######################################################    
- alias: Turn on hall light at night
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.stellar
        state: 'off'
      - condition: state
        entity_id: input_boolean.homestatus
        state: 'on'     
  action:
    - service: switch.turn_on
      entity_id: switch.stair_alcove
    - service: switch.turn_on
      entity_id: switch.front_alcove
##########################################################################################
- alias: Media Turn off hall lights if livingroom on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.stellar
    to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.stair_alcove
    - service: switch.turn_off
      entity_id: switch.front_alcove
##########################################################################################
- alias: Turn on hall lights if livingroom off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.stellar
    to: 'off'
  condition:  
    condition: sun
    after: sunset  
  action:
    - service: switch.turn_on
      entity_id: switch.stair_alcove
    - service: switch.turn_on
      entity_id: switch.front_alcove    
    
- alias: kitchen door on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.kitchen_door  
    
- alias: kitchen door off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.garage_door
    to: 'off'
    for:
      minutes: 1 
  action:
    service: light.turn_off
    entity_id: light.kitchen_door        
    
    
