######################################################
#                 Mancave Lights                     #
######################################################

##########################################################################################
- alias: turn on the mancave lights
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.mancave
    from: 'off'
    to: 'on'            
  action:
    service: light.turn_on
    entity_id: group.mancave
##########################################################################################    
- alias: mancave home
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.mancave_pir
    from: 'standby'
    to: 'motion detected'
  condition:
    condition: state
    entity_id: input_boolean.roryhome
    state: 'on'  
  action: 
    service: homeassistant.turn_on
    entity_id: input_boolean.mancave 
##########################################################################################
- alias: mancave away
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.mancave
    to: 'off'
  action: 
    - service: homeassistant.turn_off
      entity_id: input_boolean.mancave
    - service: notify.sms
      data:
        message: 'Mancave set to away'
    - service: climate.set_hold_mode
      entity_id: climate.lifesupport
      data:
        hold_mode: 'home'        
##########################################################################################
- alias: mancave comfort
  initial_state: 'on'
  trigger:
    - platform: time
    # You can also match on interval. This will match every 5 minutes
      minutes: '/5'
      seconds: 00
    - platform: state
      entity_id: input_boolean.mancave
      from: 'off'
      to: 'on'            
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.mancave_temperature 
        above: 73
      - condition: state
        entity_id: input_boolean.mancave
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        above: 65
  action:
    - service: climate.set_temperature
      data:
        temperature: 65
    - service: light.turn_on
      entity_id: light.mancave_led
      data:
        rgb_color: 36,255,22
##########################################################################################
- alias: mancave comfort off
  initial_state: 'on'
  trigger:
    - platform: time
    # You can also match on interval. This will match every 5 minutes
      minutes: '/5'
      seconds: 00
    - platform: state
      entity_id: input_boolean.mancave
      from: 'on'
      to: 'off' 
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.mancave_temperature 
        below: 73
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        above: 65
  action:
    - service: climate.SET_HOLD_MODE
      data:
        hold_mode: home
    - service: light.turn_on
      entity_id: light.mancave_led
      data:
        rgb_color: 255,17,16
##########################################################################################
- alias: set lights green if bart gets on xbox
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.a_hope_unseen
      from: 'Offline'
  condition:
    condition: state
    entity_id: input_boolean.mancave
    state: 'on'
  action:
    - service: light.hue_activate_scene
      data:
        group_name: "Man Cave"
        scene_name: "Xbox" 
##########################################################################################
- alias: turn on multisensor led w/ motion in man cave
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.mancave_pir      
    to: 'motion detected'
  action:
    service: light.turn_on
    entity_id: light.mancave_led
##########################################################################################
- alias: turn off multisensor led w/ motion in man cave
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.mancave_pir      
    to: 'standby'
  action:
    service: light.turn_off
    entity_id: light.mancave_led        
        
        
        
        
        
  