######################################################
#                 Morning                            #
######################################################
##########################################################################################     
- alias: Morning text pollen
  trigger:
    platform: time
    at: '10:00:00'
  action:
    - service: notify.smsdad
      data:
        message: "The allergy level is {{ states.sensor.pollen_level.state }}."
##########################################################################################  
- alias: Morning report 
  trigger:
    platform: time
    at: '06:15:00'
  action:
    - service: notify.sms
      data_template:
        title: "."
        message: "The High today is {{ states.sensor.dark_sky_daily_high_temperature.state }} F."
    - service: notify.sms
      data_template:
        title: "."
        message: "The low is {{ states.sensor.dark_sky_daily_low_temperature.state }} F."
    - service: notify.sms
      data_template:
        title: "."
        message: "The humidity level is {{ states.sensor.dark_sky_humidity.state }}%."
    - service: notify.sms
      data_template:
        title: "."
        message: "There is a {{ states.sensor.dark_sky_precip_probability.state }}% chance of rain."
    - service: notify.sms
      data_template:
        title: "."
        message: "The allergy level is {{ states.sensor.pollen_level.state }}."
#    - service: notify.sms
#      data_template:
#        title: "."
#        message: "You have to leave by {{ (as_timestamp(now.now()) - states.sensor.morning_commute_rory.attributes.duration.split(" ")[0] | int *60 ) | timestamp_custom("%Y-%m-%d %H:%M") }}"
- alias: Morning text pollen brennan
  trigger:
    platform: time
    at: '6:30:00'
  action:
    - service: notify.smsbrennan
      data:
        message: "The allergy level is {{ states.sensor.pollen_level.state }}."
        
- alias: 'Commute To Work (Rory)'
  initial_state: 'on'
  trigger:
    platform: template
    value_template: "{{ ((now().strftime('%H') | int) + (now().strftime('%M')|int / 60) | round(2)) > ( 8.33 - ((states.sensor.morning_commute_rory.state) | int / 60)) }}"
  condition:
    condition: and
    conditions:
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
     - condition: state
       entity_id: input_boolean.roryhome
       state: 'on'   
  action:
    service: notify.sms
    data_template:
      title: "Time to go!"
      message: >
        It will take {{ states("sensor.morning_commute_rory") }} minutes to get to work.
        
- alias: kitchen door on
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homestatus 
        state: 'on'
      - condition: time
        after: '05:00:00'
        before: '08:00:00'    
  action:
    service: light.turn_on
    entity_id: light.kitchen_door  
    
- alias: kitchen door off
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen
    to: 'off'
    for:
      minutes: 1 
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.homestatus 
        state: 'on'
      - condition: time
        after: '05:00:00'
        before: '08:00:00'
  action:
    service: light.turn_off
    entity_id: light.kitchen_door    
